apps/clientes/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^crear-cliente/',
        views.ClienteCreateView.as_view(),
        name='crear_cliente')
]

apps/main/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^inicio/',
        views.IndexTemplateView.as_view(),
        name='inicio')
]

apps/proveedores/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^crear-proveedor/',
        views.ProveedorCreateView.as_view(),
        name='crear_proveedor'),

    url(r'^crear-producto/',
        views.ProductoProveedorCreateView.as_view(),
        name='crear_producto'),

    url(r'^crear-servicio/',
        views.ServicioProveedorCreateView.as_view(),
        name='crear_servicio'),

    url(r'^lista-productos/',
        views.ProductoProveedorListView.as_view(),
        name='lista_productos'),

    url(r'^lista-servicios/',
        views.ServicioProveedorListView.as_view(),
        name='lista_servicios')
]

project/urls.py
from django.conf.urls import url, include, patterns
from django.conf.urls.static import static
from .settings import base
from django.contrib import admin
from apps.main.views import log_in as entrar, salir
from apps.utils import errors

urlpatterns = [

    #frameworks y plugins
    url(r'^admin/', admin.site.urls),
    url(r'^chaining/', include('smart_selects.urls')),

    # administrar sesiones
    url(r'^$', entrar, name='entrar'),
    url(r'^salir/', salir, name='salir'),

    # modulos
    url(r'^clientes/', include('apps.clientes.urls', namespace='clientes')),

    url(r'^proveedores/', include('apps.proveedores.urls', namespace='proveedores')),

    url(r'^inicio/', include('apps.main.urls', namespace='main')),



] + static(base.MEDIA_URL, document_root=base.MEDIA_ROOT)


handler400 = errors.error400
handler403 = errors.error403
handler404 = errors.error404
handler500 = errors.error500

apps/clientes/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from apps.utils.models import UserBase


class Cliente(UserBase):
    pass

apps/main/models.py
from django.db import models


class BaseName(models.Model):
    nombre = models.CharField(max_length=255, unique=True)

    class Meta:
        abstract = True

    def __str__(self):
        return '{0}'.format(self.nombre)

apps/clientes/forms.py
from django import forms

from apps.utils.forms import BaseUserForm
from .models import Cliente


class ClienteForm(BaseUserForm):
    title = 'Cliente'

    class Meta(BaseUserForm.Meta):
        model = Cliente

apps/main/forms.py
from django import forms

apps/clientes/views.py
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render

# Create your views here.
from django.views.generic import CreateView

from apps.clientes.forms import ClienteForm
from apps.clientes.models import Cliente


class ClienteCreateView(CreateView):
    template_name = 'forms/with_login.html'
    form_class = ClienteForm
    success_url = reverse_lazy('entrar')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = 'Crear'
        return context

apps/main/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.utils.translation import ugettext as _
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, logout, login as auth_login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.shortcuts import render, redirect


# Create your views here.


def log_in(request):
    context = {'error': False}
    if request.POST:
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                auth_login(request, user)
                if user.is_staff or user.is_superuser:
                    return redirect('admin:index')
                else:
                    return redirect('main:inicio')
            else:
                context = {'msj': _('El usuario ha sido desactivado'), 'error': True}
        else:
            context = {'msj': _('usuario o contraseña incorrecta'), 'error': True}
    return render(request, 'login_form.html', context)


@login_required
def salir(request):
    logout(request)
    return redirect('entrar')


class IndexTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'plataforma/base.html'

templates/plataforma/sidebar/cliente.html
<li>
    <a href="index.html">
        <i class="fa fa-fw fa-dashboard"></i>
        Dashboard Cliente
    </a>
</li>
<li>
    <a href="javascript:;" data-toggle="collapse" data-target="#servicios">
        <i class="fa fa-fw fa-cube"></i>
        Servicios
        <i class="fa fa-fw fa-caret-down"></i></a>
    <ul id="servicios" class="collapse">
        <li>
            <a href="#">Crear Servicios</a>
        </li>
        <li>
            <a href="#">Ver Servicios</a>
        </li>
    </ul>
</li>
<li>
    <a href="javascript:;" data-toggle="collapse" data-target="#productos">
        <i class="fa fa-fw fa-star"></i>
        Productos
        <i class="fa fa-fw fa-caret-down"></i></a>
    <ul id="productos" class="collapse">
        <li>
            <a href="#">Crear Producto</a>
        </li>
        <li>
            <a href="#">Ver Productos</a>
        </li>
    </ul>
</li>

templates/plataforma/sidebar/main.html
<div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav side-nav">
        {% if request.user.proveedor %}
            {% include 'plataforma/sidebar/proveedor.html' %}
        {% elif request.user.cliente %}
            {% include 'plataforma/sidebar/cliente.html' %}
        {% endif %}
    </ul>
</div>
<!-- /.navbar-collapse -->

templates/plataforma/sidebar/proveedor.html
<li>
    <a href="index.html">
        <i class="fa fa-fw fa-dashboard"></i>
        Dashboard proveedor
    </a>
</li>
<li>
    <a href="javascript:;" data-toggle="collapse" data-target="#servicios">
        <i class="fa fa-fw fa-cube"></i>
        Servicios
        <i class="fa fa-fw fa-caret-down"></i></a>
    <ul id="servicios" class="collapse">
        <li>
            <a href="{% url 'proveedores:crear_servicio' %}">Crear Servicios</a>
        </li>
        <li>
            <a href="{% url 'proveedores:lista_servicios' %}">Ver Servicios</a>
        </li>
    </ul>
</li>
<li>
    <a href="javascript:;" data-toggle="collapse" data-target="#productos">
        <i class="fa fa-fw fa-star"></i>
        Productos
        <i class="fa fa-fw fa-caret-down"></i></a>
    <ul id="productos" class="collapse">
        <li>
            <a href="{% url 'proveedores:crear_producto' %}">Crear Producto</a>
        </li>
        <li>
            <a href="{% url 'proveedores:lista_productos' %}">Ver Productos</a>
        </li>
    </ul>
</li>