apps/__base/api/urls.py
from django.conf.urls import url, include
from rest_framework import routers

router = routers.DefaultRouter()

urlpatterns = [

]

apps/__base/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^api/', include('apps.__base.api.urls'))
]

apps/clientes/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^crear-cliente/',
        views.ClienteCreateView.as_view(),
        name='crear_cliente')
]

apps/main/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^inicio/',
        views.IndexTemplateView.as_view(),
        name='inicio')
]

apps/proveedores/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^crear-proveedor/',
        views.ProveedorCreateView.as_view(),
        name='crear_proveedor'),

    url(r'^crear-producto/',
        views.ProductoProveedorCreateView.as_view(),
        name='crear_producto'),

    url(r'^crear-servicio/',
        views.ServicioProveedorCreateView.as_view(),
        name='crear_servicio'),

    url(r'^lista-productos/',
        views.ProductoProveedorListView.as_view(),
        name='lista_productos'),

    url(r'^lista-servicios/',
        views.ServicioProveedorListView.as_view(),
        name='lista_servicios')
]

apps/utils/urls.py
from django.conf.urls import url, include

urlpatterns = [

]

project/urls.py
from django.conf.urls import url, include, patterns
from django.conf.urls.static import static
from .settings import base
from django.contrib import admin
from apps.main.views import log_in as entrar, salir
from apps.utils import errors

urlpatterns = [

    #frameworks y plugins
    url(r'^admin/', admin.site.urls),
    url(r'^chaining/', include('smart_selects.urls')),

    # administrar sesiones
    url(r'^$', entrar, name='entrar'),
    url(r'^salir/', salir, name='salir'),

    # modulos
    url(r'^clientes/', include('apps.clientes.urls', namespace='clientes')),

    url(r'^proveedores/', include('apps.proveedores.urls', namespace='proveedores')),

    url(r'^inicio/', include('apps.main.urls', namespace='main')),



] + static(base.MEDIA_URL, document_root=base.MEDIA_ROOT)


handler400 = errors.error400
handler403 = errors.error403
handler404 = errors.error404
handler500 = errors.error500

apps/__base/models.py
from django.db import models

# Create your models here.

apps/main/models.py
from django.db import models


class BaseName(models.Model):
    nombre = models.CharField(max_length=255, unique=True)

    class Meta:
        abstract = True

    def __str__(self):
        return '{0}'.format(self.nombre)

apps/pagos/models.py
from django.db import models

# Create your models here.

apps/utils/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from apps.main.models import BaseName


class UserBase(User):
    telefono_fijo = models.PositiveIntegerField()
    telefono_celular = models.PositiveIntegerField()
    direccion = models.CharField(max_length=150)
    TIPOS = (
        ('NIT', 'NIT'),
        ('RUT', 'RUT'),
        ('CC', 'CC')
    )
    tipo_documento = models.CharField(
        max_length=5,
        choices=TIPOS
    )
    identificacion = models.CharField(
        unique=True,
        max_length=20
    )

    class Meta:
        abstract = True


class VentaItem(BaseName):
    proveedor = models.ForeignKey('proveedores.Proveedor')
    valor = models.PositiveIntegerField()

apps/compras/forms.py
from django import forms

apps/main/forms.py
from django import forms

apps/pagos/forms.py
from django import forms

apps/utils/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm


class BaseForm(forms.ModelForm):
    title = ''

    class Meta:
        model = None
        fields = '__all__'


class BaseUserForm(UserCreationForm):
    title = ''

    class Meta:
        model = None
        exclude = (
            'last_login',
            'first_name',
            'last_name',
            'is_staff',
            'is_superuser',
            'date_joined',
            'groups',
            'user_permissions',
            'password',
            'is_active',
            'email',
        )
        fields = '__all__'

apps/__base/views.py
from django.shortcuts import render

# Create your views here.

apps/compras/views.py
from django.shortcuts import render

# Create your views here.

apps/main/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.utils.translation import ugettext as _
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, logout, login as auth_login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.shortcuts import render, redirect


# Create your views here.


def log_in(request):
    context = {'error': False}
    if request.POST:
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                auth_login(request, user)
                if user.is_staff or user.is_superuser:
                    return redirect('admin:index')
                else:
                    return redirect('main:inicio')
            else:
                context = {'msj': _('El usuario ha sido desactivado'), 'error': True}
        else:
            context = {'msj': _('usuario o contraseña incorrecta'), 'error': True}
    return render(request, 'login_form.html', context)


@login_required
def salir(request):
    logout(request)
    return redirect('entrar')


class IndexTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'plataforma/base.html'

apps/pagos/views.py
from django.shortcuts import render

# Create your views here.

apps/utils/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView
from django.views.generic import ListView
from django.views.generic import UpdateView
from apps.utils.shortcuts import get_object_or_none


class BaseListView(LoginRequiredMixin, ListView):
    pass


class BaseCreateView(LoginRequiredMixin, CreateView):
    template_name = 'forms/base_form.html'

    def get_context_data(self, **kwargs):
        context = super(BaseCreateView, self).get_context_data(**kwargs)
        context['action'] = 'Crear'
        return context


class BaseListViewDinamicHeader(LoginRequiredMixin, ListView):
    context_object_name = "list"
    paginate_by = 25
    query_fields = ()
    HEADER = None

    def __init__(self):
        super(BaseListViewDinamicHeader, self).__init__()
        self.HEADER += ('Acciones',)

    def get_queryset(self):
        return self.model.objects.all()

    def get_context_data(self, **kwargs):
        context = super(BaseListViewDinamicHeader, self).get_context_data(**kwargs)
        context['header_table'] = self.get_header_table()
        return context

    def get_header_table(self):
        return self.HEADER


class DirectDeleteMixin(object):
    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class BaseUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'forms/base_form.html'

    def get_context_data(self, **kwargs):
        context = super(BaseUpdateView, self).get_context_data(**kwargs)
        context['action'] = 'Modificar'
        return context

    def get_object(self, queryset=None):
        obj = self.model.objects.get(id=self.kwargs['pk'])
        return obj

templates/index.html
<!DOCTYPE html>
<html lang="en">{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>Base Index</title>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-theme.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery-3.1.1.js' %}" type="text/javascript"></script>
</head>
<body>
    {% block main %}
    {% endblock main %}

    <script src="{% static 'js/bootstrap.js' %}" type="application/javascript"></script>

    {% block js_extra %}{% endblock js_extra %}
</body>
</html>

templates/login.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container-fluid" style="margin-top: 3%">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            {% block main %}{% endblock %}
        </div>
    </div>
</div>
</body>
</html>

templates/login_form.html
{% extends 'login.html' %}
{% block main %}
    {% load i18n %}
    <form method="post">{% csrf_token %}
        <div class="panel panel-success">
            <div class="panel-heading">
                <h2 class="text-center">Login</h2>
            </div>
            <div class="panel-body text-center">
                {% if error %}
                    <div class="alert alert-danger alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                aria-hidden="true">×</span></button>
                        <strong>{% trans 'Error' %}</strong>, {{ msj }}
                    </div>
                {% endif %}
                <div class="form-group">
                    <input type="text" placeholder="username" class="form-control" name="username" required>
                </div>
                <div class="form-group">
                    <input type="password" placeholder="password" class="form-control" name="password" required>
                </div>
            </div>
            <div class="panel-footer" align="center">
                <input type="submit" value="login" class="btn btn-success">
            </div>
        </div>
        <div class="row">
            <div class="col-md-12" align="center">
                <a href="{% url 'clientes:crear_cliente' %}" class="btn btn-primary">
                    registrase como cliente
                </a>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-md-12" align="center">
                <a href="{% url 'proveedores:crear_proveedor' %}" class="btn btn-info">
                    registrarse como proveedor
                </a>
            </div>
        </div>
    </form>
{% endblock %}